### PR TITLE
Teach boegelbot about polite and impolite requests.

### PR DESCRIPTION
**Pull request by akesandgren**
You asked for improvements...

### CODE REVIEW

**Comment by akesandgren** [comment]
Looks like you only accept PR's from yourself...

**Comment by boegel** [comment]
@akesandgren That's already broken on current `main`, haven't gotten around to fix that yet (I really should)

**Review by boegel — APPROVED** [review]
lgtm

**Comment by boegel** [comment]
@akesandgren Problems with the tests are fixed in `main`, can you sync this PR?

**Pull request merged**
